### ISSUE TITLE
Clojure and Ruby: what we can learn from each other

### ISSUE THREAD

**Issue by vemv** [RubyAndFriends/TalkSuggestions#1]
# Clojure and Ruby: what we can learn from each other

I'll present Clojure for rubyists not from a 'you should migrate' POV, but rather: what practical teachings from Clojure can you apply to your daily Ruby job?

That should include:

* The basic notions of FP, immutability and concurrency
* The Clojure community's overall approach to engineering
* backend- and frontend-specific concerns
* IDE/Editor goodness

Similarly I'll point out to some strengths from RoR which are missing in Clojure.

* Approx. duration: 30-45m
* Audience: everyone except absolute beginners

The talk is WIP and will be finished by September.

## Speaker information

* Name: Víctor M. V.
* @vemv
* https://blog.vemv.net/

About me: 

I've managed to swim between the clj and ruby communities for a number of years, constantly trying to achieve the best of the both worlds.

https://www.linkedin.com/in/vemvdotnet/

**Comment by mediafinger** [comment]
Hey Victor, thanks for filling this one out - and for offering to give a talk 👏 

We will plan the October's meeting in the next week or so. Will send you a link before we announce it.

**Comment by vemv** [comment]
Hey Andreas,

I finished authoring the core of my presentation, so it's ready. I simply should add some images to make it less boring.

Let me know if you want to have a glance at it.

Cheers - V

**Comment by mediafinger** [comment]
> Let me know if you want to have a glance at it.

While I trust you to deliver a good presentation, I'm happy to have a look, when you want to have feedback 😃

**Comment by vemv** [comment]
Thank you for making this one possible!

Looking forward to attend StartupGrind as per yesterday's `.sample`.
