### ISSUE TITLE
Diving into event-sourcing and event-driven architecture on rails

### ISSUE THREAD

**Issue by uesteibar** [RubyAndFriends/TalkSuggestions#2]
# Diving into event-sourcing and event-driven architecture on rails

I'd like to talk about my teams journey this year into event-sourcing, cqrs and event-driven architectures on rails.

I'll give a small overview of event-sourcing (and consequently a little CQRS), event-driven architectures and challenges that we faced by diving into this topics in a rails app (in a microservices environment surrounded by a bunch of other rails apps).

* Approx. duration: [ 40 minutes ]
* Audience: devs new to the topic and maybe devs familiar with the topic

The talk is in work and will be finished by date.

## Speaker information

* Name: [ Unai Esteibar ]  
* Github: [ @uesteibar ]  
* Twitter: [ @uesteibar ]

**Comment by mediafinger** [comment]
:+1:
