### ISSUE TITLE
Visual Regression Testing with NoRegrets

### ISSUE THREAD

**Issue by victormours** [RubyAndFriends/TalkSuggestions#3]
# Visual Regression Testing with NoRegrets

In this talk, I'll be introducing NoRegrets, a gem for adding visual regression testing to Capybara specs. I'll start with an explanation of visual regression testing and why we need it. Then I'll run a demonstration of the gem and how it can be used to spot the unintended consequences of a change in css. And finally, we'll dive into some interesting points of the implementation to see how some principles could be reused for other types of regression testing.

* Approx. duration: 20 minutes
* Audience: devs new to the topic

_The talk and the gem itself are in work and will be finished by date_

## Speaker information

* Name: Victor Mours
* Github: @victormours  
* Twitter: @victormours

About me:

Hi guys! We met two years ago when I came to Barcelona and did [a talk about Rails Engines](https://www.meetup.com/fr-FR/Barcelona-on-Rails/events/fdxgllyvqbtb/). It was great meeting you so I'd love to come and present this talk. :) I'm still currently living in Paris, so I'll only be in Barcelona from Dec 3rd to Dec 15th, which means I won't be there at the scheduled date of December 20th. Would you guys be willing to move the meetup date maybe from the 20th to the 13th ?

And some more info about me: I've been working at Drivy for a little while, and just recently joined Enercoop, a renewable energy provider. I'm still hosting the Paris Ruby Workshop and teaching at Le Wagon BCN from times to times.

See you soon I hope!

**Comment by dvrensk** [comment]
Hello Victor,
I'm very sorry we didn't get back to you in a timely fashion.  The organising team was a bit incoherent during December, and we ended up cancelling that month's meeting (late!).  Thanks for your kind offer, and I hope you will give us another chance in the future!

**Comment by victormours** [comment]
Hi David, no worries, i know firsthand how much trouble organizing a meetup can be, so I totally understand. :) I'll definitely ping you guys next time I'm in Barcelona.

Cheers!
