### ISSUE TITLE
From raw data to SaaS in 60 minutes

### ISSUE THREAD

**Issue by buger** [RubyAndFriends/TalkSuggestions#4]
# From raw data to SaaS in 60 minutes

In this talk, I want to show you how to go from a simple API to a powerful dashboard with analytics, usage policies, developer management, billing and public facing developer portal embedded directly to your app, with just a few lines for Ruby, and using Tyk.io as an API gateway.

* Approx. 60 minutes
* Audience: beginners

The talk is in work and will be finished by date. Will try to send it to review in a week before the date.

## Speaker information
* Name: Leonid Bugaev
* Github: @buger
* Twitter: https://twitter.com/buger

About me:
At the moment I lead distributed engineering team at Tyk.io - and build open-source API gateway.
In spare time, I build [GoReplay](https://github.com/buger/goreplay) and enjoying nomad life with my family. Have been using RoR from its first release for 7 years in a row, and switched to Go in last years.

**Comment by dvrensk** [comment]
Hey @buger, I think this sounds great!  Will you have it ready for our February session, the 21st?

**Comment by buger** [comment]
@dvrensk yes it will be ready till that time. I will send you it for review in a week before start.
